name: Run Test

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: action/checkout@main

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        uses: ./gradlew assembleDebug

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-builds
          path: |
            app/build/outputs/apk/debug/*.apk
#
#      - name: Run unit tests
#        run: ./gradlew clean testDebug