name: Run Test

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu_latest

    steps:
      - uses: action/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java_version: 17
          catch: "gradle"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew clean testDebug



